### ISSUE TITLE
Browser error when clicking on item notes

### ISSUE THREAD

**Issue by michaelphagen** [dwmorrin/gas-eco#1]
browser error when clicking on item notes: userCodeAppPanel:182 Uncaught TypeError: Cannot read property 'textContent' of undefined at HTMLDivElement.handleClickTable

**Comment by michaelphagen** [comment]
what was the original plan for saving the notes? it seems like they are saved into the DOM in itemslist, but then that list is typically cleared when it is refreshed. I have not seen where the item notes are saved, and since the itemlist is refreshed via items.foreach(populateItemList), it's cleared every time.

below are the last 5 lines of the function "populateItemList"
```
notes.setAttribute('colspan', 4);
  notes.classList.add('itemnotes');
  notes.textContent = 'Notes: ';
  noteRow.appendChild(notes);
  app.pages.form.elements.itemList.appendChild(noteRow);
```
There doesn't seem to be any loading goinmg on here, so it's just overwriting the notes everytime it refreshes.

**Comment by michaelphagen** [comment]
maybe a solution would be to add a property for items in item.gs that would contain an empty string, and then the notes would be written in there. we would only be modifying the version of the item inside the form (similar to how the manual entry works) so it shouldn't leave that particular form.

**Comment by michaelphagen** [comment]
I have a fix on my branch that makes notes a property of items. By default the value is "Notes: ", so that it is blank when first checked out. The notes are saved into the form as a property of the item within app.pages.form.elements.form.items, and is edited in the same way.

**Comment by dwmorrin** [comment]
Great, I like the progress here.
I don't recall if there was an original working version of this or not.  The file `Note.gs` reminds me that there was intention to have an abstraction of notes going on, and that might have been part of refactoring the 3 note taking cases in `app.doCommand` into something nicer.

**Comment by michaelphagen** [comment]
this was fixed with hotfix/1
