### ISSUE TITLE
Clarify the message in the Signature Modal

### ISSUE THREAD

**Issue by michaelphagen** [dwmorrin/gas-eco#103]
Requested by Michael McCoy. Include a "script" in the modal window that comes up for students who do not have a signature on file for the staff member to read explaining what the signature is for and what it means.

**Comment by dwmorrin** [comment]
### Current Text:
"A signature was not found for this person.  Please use the tablet to get the student signature then click the done button."

### First try rewrite:
"Production area policy ('the policy') acknowledgment signature not found for this person.  All persons must read the policy and have a signature on file.  Please use the tablet to show the person the policy and capture their signature.  Click the 'Signature Done/Recheck' when they are finished using the tablet."
