### ISSUE TITLE
Highlight the currently sorted column

### ISSUE THREAD

**Issue by michaelphagen** [dwmorrin/gas-eco#106]
Requested by Michael McCoy. When sorting a list of forms in OpenForms or in the Archive, there should be some indication  of which column is currently being sorted by.

**Comment by dwmorrin** [comment]
Not that it is that important, but this feature was actually requested by Noah Simon 😉

**Comment by michaelphagen** [comment]
> Not that it is that important, but this feature was actually requested by Noah Simon 😉

Thanks for the correction
