### ISSUE TITLE
displayOpenForms is overworked: separate sorting from populating

### ISSUE THREAD

**Issue by dwmorrin** [dwmorrin/gas-eco#21]
The basic refactor is actually super simple: just pull out the very last line of `Display.html::displayOpenForms`.  The resulting function is just a mutating sorter function (it sorts the given array in place).  (Consider using .slice() to copy the array inside.)

Then `grep -R displayOpenForms .` from the `js` directory and patch the code.

**Comment by michaelphagen** [comment]
Closed with hotfix/21
