### ISSUE TITLE
Need quantity entry

### ISSUE THREAD

**Issue by dwmorrin** [dwmorrin/gas-eco#25]
Items that are within the special barcode range 10000 - ?(check reserved max) shall get a dropdown menu, a la Amazon shopping cart, to change quantity.

Remove the serialized "NS" thing from Item.gs.

**Comment by michaelphagen** [comment]
this seems to have been patched when issue 25 was fixed

**Comment by dwmorrin** [comment]
I want to address the UI here

### Current behavior
Hovering over a clickable quantity in the item list gives the "text" cursor  ![image](https://user-images.githubusercontent.com/27562871/56502613-f35e3480-64e0-11e9-8799-d4ff9bcb38df.png) and otherwise does not indicate that it is clickable.

### Expected behavior
Hovering over a clickable quantity in the item list gives the "pointer" cursor ![image](https://user-images.githubusercontent.com/27562871/56502654-1b4d9800-64e1-11e9-83cd-19ebdf441a4b.png) and changes the color (highlights) the quantity text to indicate that the user should click to change.

**Comment by michaelphagen** [comment]
I agree. I'm happy to hop on that after I finish 2 emails unless you're tackling it now.

**Comment by dwmorrin** [comment]
You're already on the item note thing, right?
