### ISSUE TITLE
unlocked update button when viewing a closed form

### ISSUE THREAD

**Issue by dwmorrin** [dwmorrin/gas-eco#31]
### steps to reproduce

Not sure.  I had a new form for the class setup, I finished it, and the update button said "all changes saved" but it was unlocked and pressing it resulted in an error message.  Going to view closed forms and back to that form again, it was still unlocked.

Refreshing the page fixed the problem and restored normal behavior.

### Next steps

Need to review the button locking system.  Haven't looked at it in a long time.  Maybe there's a cleaner way to do it to avoid a bug like this.  I suspect this is something subtle about the logic not applying the "disabled" property to the button.

**Comment by michaelphagen** [comment]
I've disabled the buttons and click handlers in the archive, I want to look more over the update button's logic before calling this fixed on hotfix/31
