### ISSUE TITLE
Prevent the user from decreasing the quantity of a checked out item after the form has been updated

### ISSUE THREAD

**Issue by michaelphagen** [dwmorrin/gas-eco#41]
Requested by Michael McCoy, he pointed out that a user should not be able to reduce the quantity of a checked out item, and only able to increase the quantity.

**Comment by dwmorrin** [comment]
This may be obvious, but I would like to clarify the issue by saying the user is **free to change the quantity prior to saving.  After saving, quantity changes are validated upon saving and cannot be less than the previously saved amount.**
