### ISSUE TITLE
Close as Incomplete

### ISSUE THREAD

**Issue by michaelphagen** [dwmorrin/gas-eco#42]
Requested by Michael McCoy, he asks that the system allow a form to be closed as inconclusive, and prompt for the reason why. This should bypass the prompt to check equipment/people back in and allow the form to be closed regardless.

this should also send an email to the tech email group letting everyone know that a form was closed as incomplete

**Comment by dwmorrin** [comment]
I request this be an admin only feature, something you can only choose from an admin page.
We don't have an admin page yet, but we should open an issue for one.

I don't foresee this being a common issue, so I would prefer to let a few of these situations crop up naturally in testing and discuss how to handle them with real world examples.

I do not see an immediate benefit to this feature.

**Comment by michaelphagen** [comment]
Closing this issue because the merge of hotfix/43 into master has all the needed functionality to resolve this issue
