### ISSUE TITLE
Add "Match only forms with ALL items" to the archive search

### ISSUE THREAD

**Issue by michaelphagen** [dwmorrin/gas-eco#45]
Currently the archive search matches forms that include any of the items in the item filter.
There should be the option to only match forms that include ALL the items in the item filter, and a checkbox to switch between the two behaviors.

**Comment by dwmorrin** [comment]
This is a good enhancement.  A word of caution though: improving the search area is an endless task: it will always have room for improvement, and Michael McCoy may have endless requests in this area.  The current search area is a **minimum viable product** and I suggest sticking to the minimum here while we focus on squashing bugs prior to our real testing during summer school.
