### ISSUE TITLE
Add searching by description to archive search

### ISSUE THREAD

**Issue by michaelphagen** [dwmorrin/gas-eco#46]
Currently the archive can only search for items by itemId. Entering data into the items box should be tested both as an ItemId and as an Item description.

**Comment by dwmorrin** [comment]
Ditto my comment in issue #45 - good enhancement, but be careful going down this road.

**Comment by michaelphagen** [comment]
This is not fixed in hotfix/21. It's a small improvement, so I'll keep working on it, but this should not be closed if we merge hotfix/21 before I fix it.
