### ISSUE TITLE
student note handler in DoCommand needs better error handling

### ISSUE THREAD

**Issue by dwmorrin** [dwmorrin/gas-eco#61]
Currently, if you are taking a student note and leave the \<textarea\> blank and hit submit, you will get an ugly error message: "an error has occured[_sic_] while getting student note".

#### possible improvements:
* handling of blank notes:
  * don't accept them OR
  * accept them but either don't complain or make the error message specific (e.g. "warning: you entered a blank message.")

**Comment by michaelphagen** [comment]
current behavior on feat/43 is that blank notes are not accepted
